name: delta_dai_bim_
description: "Proyecto Delta Dai - Panel de Administración"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Plugins de Web y Utilidades
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.1
  file_picker: ^8.0.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Si tienes imágenes en una carpeta assets, descomenta las siguientes líneas:
  # assets:
  #   - assets/